name: Deploy Spanner

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@streamyard'
      - name: Install Dependencies
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Package
        run: npm pack .
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: TARBALL=$(ls -1 -t *.tgz | head -1);npm publish --access restricted "$TARBALL"
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
